### ISSUE TITLE
Writing concise CSS

### ISSUE THREAD

**Issue by jim-rosales** [Lolonado/prj-rev-bwfs-dasmoto#4]
When writing CSS if you ever find that you are writing the same style in several locations it is best to rewrite your stylesheet to make it concise and eliminate any duplicate styles. For example here:

```CSS
.brushes {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: mediumspringgreen;
}

.frames {
  font-family: Helvetica; 
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: lightcoral;
}
.paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: skyblue;
}
```

`brushes`, `frames`, and `paint` all make use of the following styles:
```CSS
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
```

The only thing that differs between the three are their background colors.

Considering this the better alternative would be to apply the desired styles in this manner:
```CSS
h3 {
  font-family: Helvetica; 
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes {
  background-color: mediumspringgreen;
}

.frames {
  background-color: lightcoral;
}
.paint {
  background-color: skyblue;
}
```

https://github.com/Lolonado/prj-rev-bwfs-dasmoto/blob/7010b88d9f48461946ba985f07a6025e46ab6401/Dasmotos%20arts%20and%20crafts/resources/style.css#L11-L15
